modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/uecasm/rs4cc/issues"
[[mods]]
modId="storage4computercraft"
version="${version}"
displayName="Storage for ComputerCraft"
updateJSONURL="https://raw.githubusercontent.com/uecasm/rs4cc/trunk/update.json"
displayURL="https://github.com/uecasm/rs4cc"
logoFile="logo.png"
credits="Refined Storage, Applied Energistics 2, and ComputerCraft"
authors="Mirality"
description='''
This adds a "Refined Storage Peripheral" block that can be accessed as a ComputerCraft peripheral, allowing computers and turtles access to a wide range of functions in Refined Storage.
'''
[[dependencies.storage4computercraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storage4computercraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storage4computercraft]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.94.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.storage4computercraft]]
    modId="refinedstorage"
    mandatory=false
    versionRange="[1.9.10,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.storage4computercraft]]
    modId="appliedenergistics2"
    mandatory=false
    versionRange="[8.3.0,9.0)"
    ordering="AFTER"
    side="BOTH"
